<?php

function islandora_batch_ingest_menu() {
  $items['islandora/collection/batch'] = array(
    'title' => t('Harvest into Collection'),
    'page callback' => 'get_collection_batch_form',
    'type' => MENU_CALLBACK,
    'access arguments' => array('create batch process'),
  );
  return $items;
}

function islandora_batch_ingest_perm() {
  return array(
    'create batch process',
  );
}

function islandora_batch_ingest_islandora_collection_mangement($pid) {
  global $user;
  if (user_access('create batch process')) {
    return l('Batch Ingest', "islandora/collection/batch/$pid");
  }
}

function get_collection_batch_form($pid) {
  module_load_include('inc', 'islandora_batch_ingest', 'BatchIngest');
  module_load_include('inc', 'islandora_harvester', "harvest_form");
  return drupal_get_form('batch_creation_form', $pid);
}